
help:
	@echo "Usage: make [topic_1 | topic_2 | topic_3 | topic_4]"

topic_1:
	python main.py --topic "损失函数" --output_file 1.md --lang english

topic_2:
	python main.py --topic "Text2SQL研究现状如何，面临哪些挑战？" --output_file 2.md --lang english

topic_3:
	python main.py --topic "有哪些方法可以提升大模型的规划能力，各自优劣是什么？" --output_file 3.md --lang english

topic_4:
	python main.py --topic "多模态大模型的技术发展路线是什么样的？" --output_file 4.md --lang english


