name: natural_reasoning_finance
data_source: /opt/local/datasets/llm-reasoning/natural_reasoning_finance
dataset_name: default
input_key: question
output_key: answer
ability: finance
reward_style: rule
splits:  
  - train
  - test
output_format: parquet
extract_answer: true
format_prompt: true
custom_params:
  answer_pattern: "\\$\\\\boxed{(.+?)}\\$\\.$"
  prompt_template: "Let's think step by step. At the very end of the reply, please strictly provide the answer in the format $\\boxed{}$.\n\nExample of an answer:\n$\\boxed{A}.\n\n${question}"
