evaluator_name: "tooleval_gpt-3.5-turbo_fn"
registered_cls_name: "OpenAIEvaluator"
prompt_template: "template.txt"
fn_completions: "openai_completions"
apis_json: "your/path/to/api_pool.json"
completions_kwargs:
  model: "gpt-3.5-turbo-16k"
  max_tokens: 100
  temperature: 0
  timeout: 10
  function_call:
    name: "choose_preference"
  functions:
    - name: "choose_preference"
      description: "Choose the preferred answer for the query within all given answers."
      parameters:
        type: "object"
        properties:
          preference:
            type: "number"
            description: "The index of the preferred answer in all given answers."
        required: [ "preference" ]
fn_completion_parser: "index_parser"
batch_size: 1
