help:
	@echo "Please use \`make <target>' where <target> is one of the following: deepseek_coder"

create_nexusraven_v2_13b:
		ollama create uukuguy/nexusraven-v2-13b:Q4_K_M -f Modelfile.nexusraven-v2-13b.Q4_K_M

run_nexusraven_v2_13b:
		ollama run uukuguy/nexusraven-v2-13b:Q4_K_M 

create_dolphin-2_6-mistral-7b-dpo:
		ollama create uukuguy/dolphin-2_6-mistral-7b-dpo:Q8_0 -f Modelfile.dolphin-2_6-mistral-7b-dpo.Q8_0

create_dolphin_2_6_phi_2:
		ollama create uukuguy/dolphin-2_6-phi-2:Q8_0 -f Modelfile.dolphin_2_6_phi_2.Q8_0

run_dolphin_2_6_phi_2:
		ollama run uukuguy/dolphin-2_6-phi-2:Q8_0 

create_phi_2:
		ollama create uukuguy/phi-2:Q8_0 -f Modelfile.phi_2_Q8_0

run_phi_2:
		ollama run uukuguy/phi-2:Q8_0 

create_speechless_llama2_super_long_name:
		ollama create uukuguy/speechless-llama2-super-long-name:13b.Q8_0 -f Modelfile.speechless_llama2_super_long_name_13b_Q8_0

run_speechless_llama2_super_long_name:
		ollama run uukuguy/speechless-llama2-super-long-name:13b.Q8_0

create_mistral:
		ollama create uukuguy/mistral:7b-instruct-v0.2.Q8_0 -f Modelfile.mistral_7b_instruct_v0.2_Q8_0

run_mistral:
		ollama run uukuguy/mistral:7b-instruct-v0.2.Q8_0

create_speechless_mistral_moloras:
		ollama create uukuguy/speechless-mistral-moloras:7b.Q4_K_M -f Modelfile.speechless_mistral_moloras_7b_Q4_K_M

run_speechless_mistral_moloras:
		ollama run uukuguy/speechless-mistral-moloras:7b.Q4_K_M

create_speechless_code_mistral:
		ollama create uukuguy/speechless-code-mistral:7b_v1.0.Q4_K_M -f Modelfile.speechless_code_mistral_7b_v1.0_Q4_K_M

run_speechless_code_mistral:
		ollama run uukuguy/speechless-code-mistral:7b_v1.0.Q4_K_M 

create_speechless_tora_code:
		ollama create uukuguy/speechless-tora-code:7b-v1.0.Q8_0 -f Modelfile.speechless_tora_code_7b_v1.0_Q8_0

run_speechless_tora_code:
		ollama run uukuguy/speechless-tora-code:7b-v1.0.Q8_0

create_deepseek_coder:
		ollama create deepseek_coder:6.7b-instruct.Q8_0 -f Modelfile.deepseek_coder_6.7b_instruct_Q8_0

run_deepseek_coder:
		ollama run deepseek_coder:6.7b-instruct.Q8_0
