help:
	@echo "Please use \`make <target>' where <target> is one of the following: deepseek_coder"

create_mistral:
		ollama create uukuguy/mistral:7b-instruct-v0.2.Q8_0 -f Modelfile.mistral_7b_instruct_v0.2_Q8_0

run_mistral:
		ollama run uukuguy/mistral:7b-instruct-v0.2.Q8_0

create_deepseek_coder:
		ollama create deepseek_coder:6.7b-instruct.Q8_0 -f Modelfile.deepseek_coder_6.7b_instruct_Q8_0

run_deepseek_coder:
		ollama run deepseek_coder:6.7b-instruct.Q8_0
