
help:
	@echo "Usage: make [target]"
	@echo "Targets:"
	@echo "  preprocess_data: Preprocess the data"
	@echo "  train: Train the general reasoning model"

preprocess_data:
	python data_preprocess.py

train:
	bash train_general_reasoner.sh