help:
	@echo "Usage: make [run]"

demo1:
	python literature_review.py \
		--do_summary \
		--query "损失函数" \
		--review_type "concept" \

demo2:
	python literature_review.py \
		--do_summary \
		--query "Text2SQL研究现状如何，面临哪些挑战？" \
		--review_type "status" \

demo3:
	python literature_review.py \
		--do_summary \
		--query "有哪些方法可以提升大模型的规划能力，各自优劣是什么？" \
		--review_type "comparison" \

demo4:
	python literature_review.py \
		--do_summary \
		--query "多模态大模型的技术发展路线是什么样的？" \
		--review_type "timeline" \

run:
	python literature_review.py
